{% set name = "napari-patchcreator" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-patchcreator-{{ version }}.tar.gz
  sha256: 08fc176d3224430fbe47d2af9664df8b571216402b68e84ca6f30aeedb384ff4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.8,<3.11
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.8,<3.11

test:
  imports:
    - napari_patchcreator
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/juglab/napari-patchcreator
  summary: A simple plugin to use with napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
